collections:
  - name: community.windows
    source: https://galaxy.ansible.com
    
  - name: ansible.windows
    source: https://galaxy.ansible.com
  
  - name: community.general
    source: https://galaxy.ansible.com

  - name: containers.podman
    source: https://galaxy.ansible.com
  
  - name: community.general.docker
    source: https://galaxy.ansible.com