---
- name: Deploy EC2 
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Deploy EC2
    local_action: ec2 
      keypair="{{eckeyname}}"
      instance_type="{{instanceType}}"
      image="{{amiId}}"
      wait=yes
      group="{{groupName}}"
      count="{{instanceCount}}"
      vpc_subnet_id="{{vpcsubnetid}}"
      assign_public_ip=yes
      region="{{aws_region}}"
      zone="{{aws_zone}}"
