all:
    children:
        k8s:
            controllers:
                hosts:
                    10.255.255.67:
                    10.255.255.79:

            nodes:
                hosts:
                    10.255.255.81:
                    10.255.255.100:
    vars:
        ansible_connection: ssh 
        ansible_user: root
        ansible_ssh_pass: Lobomon42! 
