all:
    children:
        k8s:
            hosts:
                10.255.255.67:
                10.255.255.79:
                10.255.255.81:
                10.255.255.100:
        k8s_controllers:
            hosts:
                10.255.255.67:
                10.255.255.79:

        k8s_nodes:
            hosts:
                10.255.255.81:
                10.255.255.100:
    vars:
        ansible_connection: ssh 
        ansible_user: root
        ansible_ssh_pass: Lobomon42! 
