---
- name: "Run {{ noaa_container_name }}" 
  containers.podman.podman_container:
    name: "{{ noaa_container_name }}_{{ nix_timestamp }}"
    image: "{{ noaa_container_image }}"
    state: started
    env_file: "{{ noaa_env_path }}"
        networks:
          - name: "{{ noaa_network_name }}"
    tty: true
    rm: false
