---
- name: "Run {{ noaa_container_name }}"
  community.docker_container:
    name: "{{ noaa_container_name }}_{{ nix_timestamp }}"
    image: "{{ noaa_container_image }}"
    state: started
    env_file: "{{ noaa_env_path }}"
    networks:
      - name: "{{ noaa_network_name }}"
    tty: true
    auto_remove: false
    cleanup: false
    detach: true
